app:
  domain: ${DOMAIN}
  version: ${VERSION}

  api:
    context: "/api/${app.version}"
    url: ${app.domain}${app.api.context}

  cors:
    allowed-origin-patterns:
      - ${DOMAIN_CLIENT}
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - Content-Type
      - Authorization
      - X-Requested-With
    exposed-headers:
      - Authorization
      - X-Total-Count
    allow-credentials: true
    max-age: 3600

  docs:
    swagger:
      openapi:
        server:
          url: ${app.domain}
          description: "Development environment"
        info:
          title: "Tutorial Management API"
          version: "1.0"
          description: "This API exposes endpoints to manage tutorials."
          terms-of-service: "localhost"
          contact:
            name: "ndinhnguyen"
            email: "ndinhnguyen.work@gmail.com"
            url: "dev"
          license:
            name: "MIT License"
            url: "https://choosealicense.com/licenses/mit/"

spring:
  config:
    import: optional:file:./dev.env[.properties]

  docker:
    compose:
      enabled: false

  application:
    name: dev-store-api

  profiles:
    active: ${PROFILES}

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

  jwt:
    expiration: ${JWT_EXPIRATION} # 15 minutes
    refresh-expiration: ${JWT_REFRESH_EXPIRATION} # 14 days
    secret-key: ${JWT_SECRET_KEY}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
